test(vss-build-check): transfer script to bash

diff --git a/.github/workflows/vss-build-check.yml b/.github/workflows/vss-build-check.yml
--- a/.github/workflows/vss-build-check.yml
+++ b/.github/workflows/vss-build-check.yml
@@ -22,17 +22,35 @@ jobs:
               uses: ilammy/msvc-dev-cmd@v1
 
             - name: Building project
+              shell: bash
               run: |
                   msbuild src/bios.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
-                  tree /f
 
-            - name: Set outputs
+            - name: Verify build outputs
+              shell: bash
+              run: |
+                  expected=(
+                      "src/x64/Release/bios.exe"
+                  )
+
+                  for file in "${expected[@]}"; do
+                      if [[ ! -f "$file" ]]; then
+                          echo "::error::Build output missing: $file"
+                          exit 1
+                      else
+                          echo "OK: $file"
+                      fi
+                  done
+
+            - name: Compute Commit SHA
               id: vars
-              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+              shell: bash
+              run: |
+                  echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
 
             - name: Archive artifact
               uses: actions/upload-artifact@v4
               with:
                   name: bios_${{ steps.vars.outputs.sha_short }}
                   path: |
-                      src/built/DragonBurn-usermode.exe
+                      src/x64/Release/bios.exe
